<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_report_app_description'] = 'Отчет по сети показывает информацию о пропускной способности сети и всех ваших сетевых интерфейсов.';
$lang['network_report_app_name'] = 'Отчет по сети';
