#!/usr/clearos/sandbox/usr/bin/php
<?php

/**
 * Database import tool for network traffic.
 *
 * @category   apps
 * @package    network-report
 * @subpackage scripts
 * @author     ClearCenter <developer@clearcenter.com>
 * @copyright  2012 ClearCenter
 * @license    http://www.clearcenter.com/app_license ClearCenter license
 * @link       http://www.clearcenter.com/support/documentation/clearos/network_report/
 */

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// T R A N S L A T I O N S
///////////////////////////////////////////////////////////////////////////////

clearos_load_language('base');
clearos_load_language('network_report');

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

use \clearos\apps\base\Script as Script;
use \clearos\apps\network_report\Network_Report as Network_Report;

clearos_load_library('base/Script');
clearos_load_library('network_report/Network_Report');

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

$script = new Script();
$report = new Network_Report();
if ($script->lock() !== TRUE) {
    echo lang('base_script_already_running') . "\n";
    exit(0);
} else {
    try {
        $report->insert_data();
        $script->unlock();
        exit(0);
    } catch (Exception $e) {
        echo clearos_exception_message($e) . "\n";
        $script->unlock();
        exit(1);
    }
}

// vim: syntax=php ts=4
