<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_report_app_description'] = 'The Network Report provides network throughput information on all your network interfaces.';
$lang['network_report_app_name'] = 'Network Report';
