<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_report_app_description'] = 'Raport sieci dostarcza informacje o przepustowości na wszystkich interfejsach sieciowych.';
$lang['network_report_app_name'] = 'Raport sieci';
